In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\Documents\PROJECT\credit risk project\credit_risk.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           50000 non-null  int64
 1   age                   50000 non-null  int64
 2   gender                50000 non-null  object
 3   annual_income         50000 non-null  float64
 4   employment_type       50000 non-null  object
 5   loan_amount           50000 non-null  float64
 6   loan_term_months      50000 non-null  int64
 7   interest_rate         50000 non-null  float64
 8   credit_score          50000 non-null  float64
 9   previous_defaults     50000 non-null  int64
 10  loan_purpose          50000 non-null  object
 11  debt_to_income_ratio  50000 non-null  float64
 12  monthly_installment   50000 non-null  float64
 13  default_flag          50000 non-null  int64
 14  loan_status           50000 non-null  object
 15  outstanding_balance   50000 non-null  float64
dtypes: float64(7), int64(5), object(4)
memory usage: 6.1+ MB

In [5]:
df.shape

(50000, 16)

In [6]:
df.describe()

,customer_id,age,annual_income,loan_amount,loan_term_months,interest_rate,credit_score,previous_defaults,debt_to_income_ratio,monthly_installment,default_flag,outstanding_balance
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
mean,25000.500000,42.492940,60008.362474,15176.611624,36.061440,12.471888,649.427297,0.297740,0.293233,576.380493,0.18078,4727.624982
std,14433.901067,12.659787,19827.307193,7640.664194,16.957209,4.324201,69.451988,0.547263,0.211111,500.045563,0.38484,5108.187954
min,1.000000,21.000000,15000.000000,2000.000000,12.000000,5.000033,357.879814,0.000000,0.050000,33.333333,0.00000,0.121429
25%,12500.750000,32.000000,46367.345936,9616.708683,24.000000,8.711107,602.420291,0.000000,0.153824,244.990854,0.00000,1270.866121
50%,25000.500000,43.000000,59838.573905,14986.612343,36.000000,12.456131,649.694983,0.000000,0.250218,417.455495,0.00000,3080.048086
75%,37500.250000,53.000000,73409.910602,20381.785779,48.000000,16.216633,696.618865,1.000000,0.373885,728.769954,0.00000,6097.882555
max,50000.000000,64.000000,137201.782388,53412.116455,60.000000,19.999131,850.000000,6.000000,1.500000,3831.312339,1.00000,40346.389976

In [7]:
df["default_flag"].value_counts(normalize=True) * 100

default_flag
0    81.922
1    18.078
Name: proportion, dtype: float64

In [19]:
df.credit_score.min()

357.87981388495774

In [20]:
df.credit_score.max()

850.0

In [8]:
df["credit_band"] = pd.cut(
    df["credit_score"],
    bins=[300, 580, 670, 740, 850],
    labels=["Poor", "Fair", "Good", "Excellent"]
)

df.groupby("credit_band")["default_flag"].mean() * 100

C:\Users\ANIKET\AppData\Local\Temp\ipykernel_11644\4249918585.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("credit_band")["default_flag"].mean() * 100

credit_band
Poor         38.597154
Fair         16.258450
Good         11.820953
Excellent    11.640867
Name: default_flag, dtype: float64

In [14]:
df.annual_income.min()

15000.0

In [15]:
df.annual_income.max()

137201.78238781606

In [16]:
df["income_group"] = pd.cut(
    df["annual_income"],
    bins=[0, 50000, 90000,  200000],
    labels=["Low Income", "Middle Income",  "High Income"]
)

df.groupby("income_group")["default_flag"].mean() * 100

C:\Users\ANIKET\AppData\Local\Temp\ipykernel_11644\1054689405.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("income_group")["default_flag"].mean() * 100

income_group
Low Income       20.541269
Middle Income    16.895316
High Income      17.561260
Name: default_flag, dtype: float64

In [17]:
df["income_group"].value_counts()

income_group
Middle Income    30979
Low Income       15593
High Income       3428
Name: count, dtype: int64

In [21]:
df.groupby("employment_type")["default_flag"].mean() * 100

employment_type
Business         14.938575
Salaried         15.166486
Self-Employed    15.246001
Unemployed       44.297030
Name: default_flag, dtype: float64

In [22]:
df.loan_amount.min()

2000.0

In [23]:
df.loan_amount.max()

53412.11645545517

In [24]:
df["loan_amount_band"] = pd.cut(
    df["loan_amount"],
    bins=[0, 10000, 20000, 50000, 100000],
    labels=["Small Loan", "Medium Loan", "Large Loan", "Very Large"]
)

df.groupby("loan_amount_band")["default_flag"].mean() * 100

C:\Users\ANIKET\AppData\Local\Temp\ipykernel_11644\3124136178.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("loan_amount_band")["default_flag"].mean() * 100

loan_amount_band
Small Loan     17.225598
Medium Loan    17.656872
Large Loan     19.674968
Very Large      0.000000
Name: default_flag, dtype: float64

In [25]:
df["loan_amount_band"].value_counts()

loan_amount_band
Medium Loan    23379
Small Loan     13329
Large Loan     13291
Very Large         1
Name: count, dtype: int64

In [26]:
pd.crosstab(
    df["credit_band"],
    df["employment_type"],
    values=df["default_flag"],
    aggfunc="mean"
) * 100

employment_type   Business   Salaried  Self-Employed  Unemployed
credit_band
Poor             34.813926  36.103370      35.136856   67.107001
Fair             13.378437  13.337431      13.819705   41.556728
Good              8.518645   8.767047       8.360244   38.671875
Excellent         7.768924   8.505263       9.562564   39.337474

In [27]:
def risk_category(row):
    if row["credit_band"] == "Poor" and row["employment_type"] == "Unemployed":
        return "High Risk"
    elif row["credit_band"] == "Poor":
        return "High Risk"
    elif row["credit_band"] == "Fair" and row["debt_to_income_ratio"] > 0.6:
        return "Medium Risk"
    elif row["previous_defaults"] > 0:
        return "Medium Risk"
    else:
        return "Low Risk"

df["risk_category"] = df.apply(risk_category, axis=1)

df["risk_category"].value_counts(normalize=True) * 100

risk_category
Low Risk       60.032
Medium Risk    24.086
High Risk      15.882
Name: proportion, dtype: float64

In [28]:
df.groupby("risk_category")["default_flag"].mean() * 100

risk_category
High Risk      38.597154
Low Risk        6.190032
Medium Risk    34.177531
Name: default_flag, dtype: float64

In [29]:
from sqlalchemy import create_engine
import pandas as pd

# Connection details
username = "root"
password = "maheshwari%401129"   # @ replaced with %40
host = "localhost"
port = "3306"
database = "project"   # use your real DB name

# Create engine
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

print("Connected to MySQL!")

# Load dataframe to MySQL
df.to_sql(
    name="credit_risk",
    con=engine,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

# Test query
pd.read_sql("SELECT * FROM credit_risk LIMIT 5;", engine)

Connected to MySQL!
Table created successfully!

,customer_id,age,gender,annual_income,employment_type,loan_amount,loan_term_months,interest_rate,credit_score,previous_defaults,loan_purpose,debt_to_income_ratio,monthly_installment,default_flag,loan_status,outstanding_balance,credit_band,income_group,loan_amount_band,risk_category
0,1,59,Male,36984.519826,Business,11880.734718,60,16.764991,649.148189,0,Personal,0.321235,198.012245,0,Fully Paid,2669.548555,Fair,Low Income,Medium Loan,Low Risk
1,2,49,Female,40998.402933,Salaried,2000.000000,12,18.547248,702.139751,0,Car,0.050000,166.666667,0,Fully Paid,184.567205,Good,Low Income,Small Loan,Low Risk
2,3,35,Female,60474.625757,Salaried,17408.977529,48,18.767469,721.326783,1,Car,0.287872,362.687032,0,Fully Paid,4692.601958,Good,Middle Income,Medium Loan,Medium Risk
3,4,63,Male,82410.830370,Salaried,19732.734677,48,15.737889,675.660033,1,Car,0.239443,411.098639,0,Fully Paid,2544.172843,Good,Middle Income,Medium Loan,Medium Risk
4,5,28,Female,52457.013233,Business,27477.969922,48,18.897376,665.537850,1,Car,0.523819,572.457707,0,Fully Paid,5800.223962,Fair,Middle Income,Large Loan,Medium Risk